--- !ruby/object:VR_ENV
width: 1113
height: 666
panel_pos: 360
run_command_line: ruby tictactoe
open_files:
- "/home/eric/visualruby/tictactoe/tictactoe.gemspec"
- "/home/eric/visualruby/tictactoe/README.md"
open_folders:
- "/home/eric/visualruby/tictactoe"
current_file: "/home/eric/visualruby/tictactoe/README.md"
rdoc_command_line: rdoc -x README
settings_file_version: 1
builder: !ruby/object:Gtk::Builder {}
