--- !ruby/object:VR_ENV
browser: firefox
width: 1241
height: 774
panel_pos: 544
backup_path: C:/Users/Randall
tab_spaces: 2
run_command_line: ruby main.rb
open_files:
- C:/Users/Randall/visualruby/tictactoe/bin/tictactoe.rb
- C:/Users/Randall/visualruby/tictactoe/bin/Board.rb
open_folders:
- C:/Users/Randall/visualruby/tictactoe
- C:/Users/Randall/visualruby/tictactoe/bin
- C:/Users/Randall/visualruby/tictactoe/bin/glade
current_file: C:/Users/Randall/visualruby/tictactoe/bin/tictactoe.rb
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
